version: '3.8'

services:
  sample-dapp:
    build:
      context: .
      dockerfile: web-app/Dockerfile
      args:
        - VITE_COUNTER_CONTRACT_ADDRESS=${VITE_COUNTER_CONTRACT_ADDRESS}
        - VITE_PRIVIDIUM_RPC_URL=${VITE_PRIVIDIUM_RPC_URL}
        - VITE_CHAIN_ID=${VITE_CHAIN_ID}
        - VITE_CHAIN_NAME=${VITE_CHAIN_NAME}
        - VITE_NATIVE_CURRENCY_SYMBOL=${VITE_NATIVE_CURRENCY_SYMBOL}
        - VITE_AUTH_BASE_URL=${VITE_AUTH_BASE_URL}
        - VITE_PRIVIDIUM_API_URL=${VITE_PRIVIDIUM_API_URL}
        - VITE_CLIENT_ID=${VITE_CLIENT_ID}
        - VITE_COMPANY_NAME=${VITE_COMPANY_NAME}
        - VITE_ACCENT_COLOR=${VITE_ACCENT_COLOR}
        - VITE_COMPANY_ICON=${VITE_COMPANY_ICON}
    ports:
      - "4000:4000"
    env_file:
      - .env
