[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Dependencies for forge install
[dependencies]
forge-std = "foundry-rs/forge-std@v1.7.3"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
